# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: 0.4
  joint_a2: 1.5
  joint_a3: 1.46
  joint_a4: 1.12
  joint_a5: 2.77
  joint_a6: 1.8
  joint_a7: -1.8
